version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    volumes:
      - jenkins_home:/var/jenkins_home
    expose:
      - 8080
    networks:
      - dokploy-network
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.${HASH}.entrypoints=websecure
      - traefik.http.routers.${HASH}.rule=Host(`${JENKINS_HOST}`)
      - traefik.http.services.${HASH}.loadbalancer.server.port=8080

volumes:
  jenkins_home: {}

networks:
  dokploy-network:
    external: true